version: "3.3"

services:

  timezoneapp:
    build: ./
    container_name: timezoneapp
    restart: on-failure
    env_file:
      - ./.env
    expose:
      - ${NODE_LOCAL_PORT}
    volumes:
      - ./:/code
    environment:
        VIRTUAL_HOST: timezone.jojochan.top
        DB_HOST: mongo
        DB_PORT: ${MONGODB_DOCKER_PORT}
        DB_NAME: ${MONGODB_DATABASE}
        DB_USER: ${MONGODB_USER}
        DB_PASSWORD: ${MONGODB_PASSWORD}
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    volumes:
      - ~/data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

networks:
  default:
    external:
      name: nginx-proxy